### ISSUE TITLE
Wi-Fi Module (to remove or not to remove)

### ISSUE THREAD

**Issue by AlperenAkkuncu** [AlperenAkkuncu/PlainDAQ#1]
Someone suggested me to remove the Wi-Fi module because one can buy a raspberry pico W and have the Wi-Fi capability, so there is no point having it in the board.

I've been thinking about removing it and adding a new feature.

What do you guys think?

**Comment by avehbiaslanturk** [comment]
Yeah it might be good idea but first you should be sure that if it will be able to meet your needs in this project.

**Comment by Derfboy** [comment]
Would definitely recommend removing it but also maybe having a fork that keeps it in for those of us who can't get our hands on the new Pico W.

**Comment by Blaster1920** [comment]
I would remove it too.
